### PR TITLE
Design game registration + translations

### PR DESCRIPTION
**Pull request by barbayjuliette**
Changed the design of the game and tournament registration to include the rules.
Added more translations.

- Make sure no translations are missing, and there is no plain text in html, only translations
- I still have to see how the design looks on the VM. Will test next week.

Merge this branch only after my other branches are merged!!!

### CODE REVIEW

**Comment by barbayjuliette** [comment]
@chinwenkai Do not close PR if it is not merged. Just leave your review.

**Comment by chinwenkai** [comment]
If I change language just before starting a game. The spacebar will not work to start the game.
However, seems like a small issue as it may not be reasonable to change language just before a game or during the game.

**Comment by chinwenkai** [comment]
Ok. Other than that, no missed out translation for both Chrome and Firefox

**Comment by barbayjuliette** [comment]
@chinwenkai Fixed. Let me know if okay

**Comment by chinwenkai** [comment]
Yes. It is working now. Both for changing language before and during game.

**Comment by barbayjuliette** [comment]
I added:
- When I leave the game by clicking on back button or link, it still keeps the score of the tournament. 
@chinwenkai Can you test many games and tournaments, by leaving page / navigating around, going back and forth several times and make sure that the score is still correct

**Comment by chinwenkai** [comment]
Yes. the scores are kept even if I press back or next game button.
However, if I complete a game and press back instead of new game, the pages will be in greyish mode and I need to refresh to continue. The scores will still be recorded.

**Review by chinwenkai — APPROVED** [review]

**Pull request merged**
