### PR TITLE
User status update

### PR DESCRIPTION
**Pull request by barbayjuliette**
- Added an event listener: when a logged in user clicks on a link it will make an API call, so it keeps its status as online.
- If no API call, in 1 minute, user shows as offline in database.
- Removed unnecessary Bootstrap in index and some console.log

Tests:
Make sure the user online status is correct in the database. Check after clicking on links/button, (console.log: User online call)
but not when logged out. 
Check after one minute of inactivity then click on a button

### CODE REVIEW

**Comment by chinwenkai** [comment]
Hi. The language tab seems to some issues.

**Comment by barbayjuliette** [comment]
> Hi. The language tab seems to some issues.

What's the issue?

**Comment by chinwenkai** [comment]
The three languages tab does not drop down and unable to choose language

**Comment by barbayjuliette** [comment]
@chinwenkai 
I checked and it works for me.
Can you show me a video of the problem and any errors in the console?

**Comment by chinwenkai** [comment]
Ok. The language issue doesn't seem to repeat. Have checked the online status with 1 min logout. It is working

**Review by chinwenkai — APPROVED** [review]

**Pull request merged**
